run:
  timeout: 5m
  skip-files:
    - generated.*

issues:
  new: true
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
  disable:
    - deadcode
    - errcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/n0trace/caddy-opentracing
  govet:
    check-shadowing: true
  whitespace:
    multi-func: true
    multi-if: true
  lll:
    line-length: 100
  gomnd:
    settings:
      mnd:
        checks: case,condition,return
  goconst:
    ignore-tests: true
  gocyclo:
    min-complexity: 30
